spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///C:/Users/Usuario/Downloads/project/4.config-data
  security:
    user:
      name: ${CONFIG_USER}
      password: ${CONFIG_PASSWORD}
server:
  port: 9000


